#server.port=8081
#spring.application.name=nacos-provider
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#management.endpoints.web.exposure.include=*
server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        server-addr: 123.57.83.62:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'