server:
  port: 80

spring:
  application:
    name: cloud-consumer-payment
  zipkin:
    base-url: http://localhost:9411 #zipkin服务
  sleuth:
    sampler:
      probability: 1  #采样率值介于0到1之间，1则表示全部采集
  cloud:
    consul:
      host: 123.57.83.62
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-agent-address: true
        ip-address: 121.71.196.0  #注册服务ip
        #port: 80
        hostname: 121.71.196.0 #实例服务器地址
        instance-id: consulcustomer80 #实例id
