server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #git clone git@github.com:jolan80l/springcloud-config.git
          uri: https://github.com/jolan80l/springcloud-config.git
          #http://config-3344.com:3344/master/config-dev.yml
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: 123.57.83.62
    port: 5672
    username: admin
    password: admin
    #curl -X POST "http://113.45.229.5:33344/actuator/bus-refresh"
#    curl -X POST "http://113.45.229.5:33344/actuator/bus-refresh/cloud-client:3355"   #指定通知

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka



management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"