server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: jolan_tx_group
    nacos:
      discovery:
        server-addr: 123.57.83.62:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://123.57.83.62:3306/seata_order?useUnicode=true&characterEncoding-utf-8&useSSL=false
    username: seata_order
    password: seata_order



mybatis:
  mapperLocations: classpath:mapper/*.xml

#management:
#  endpoints:
#    web:
#      exposure:
feign:
  hystrix:
    enabled: false
#        include: '*'