server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service

  cloud:
    nacos:
      discovery:
        server-addr: 123.57.83.62:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel dashboard地址
        port: 8719  #默认8719端口，加入被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: 123.57.83.62:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data_type: json
            rule-type: flow

#  [
#    {
#      "resource":"/rateLimit/byUrl", 资源名称
#      "limitApp":"default", 来源应用
#      "grade":1, 阈值类型。0表示线程数，1表示QPS
#      "count":1, 单机阈值
#      "strategy":0, 流控模式。0表示直接，1表示关联，2表示链路
#      "controlBehavior":0, 流控效果。0表示快速失败，1表示Warm Up，2表示排队等待
#      "clusterModle":false 是否集群
#    }
#  ]

management:
  endpoints:
    web:
      exposure:
        include: '*'